### ISSUE TITLE
Ktor 3 support for cohort-ktor

### ISSUE THREAD

**Issue by dmitry-oshurkov** [sksamuel/cohort#79]
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/ktor/server/routing/RoutingKt
	at com.sksamuel.cohort.PluginKt$Cohort$2.invoke(plugin.kt:14)
	at com.sksamuel.cohort.PluginKt$Cohort$2.invoke(plugin.kt:11)
	at io.ktor.server.application.CreatePluginUtilsKt.setupPlugin(CreatePluginUtils.kt:276)
	at io.ktor.server.application.CreatePluginUtilsKt.createPluginInstance(CreatePluginUtils.kt:245)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.ApplicationPluginImpl.install(CreatePluginUtils.kt:83)
	at io.ktor.server.application.ApplicationPluginImpl.install(CreatePluginUtils.kt:71)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
```

**Comment by sksamuel** [comment]
2.6.0 now released
